name: Delete old workflow runs
on:
  schedule:
    - cron: '0 0 * * 0' # Runs automatically every Sunday at midnight
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3 # Deletes any runs older than 3 days
          keep_minimum_runs: 5 # Always keeps the 5 most recent runs, just in case
