name: Cleanup workflow history (temporary)

on:
  push:
    branches:
      - cleanup/history-runner
    paths:
      - '.github/.cleanup-history-trigger'

permissions:
  actions: write
  contents: read

jobs:
  delete-completed-history:
    runs-on: ubuntu-latest
    steps:
      - name: Delete completed workflow run history
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
